version: '3.9'
services:
  backend:
    image: connected-app
    restart: always
    ports:
      - "127.0.0.1:9999:9999"
    environment:
      PSQL_URL: jdbc:postgresql://psql:5432/connected-db
      PSQL_USER: connected-admin
      PSQL_PASSWORD: Str0ngP@ss_Ul1!Ul1!
      SERVER_HOST: 127.0.0.1
      SERVER_PORT: 9999
      GMAIL_USER:
      GMAIL_PASS:
      GMAIL_ADDR:

  psql:
    image: postgres
    restart: always
    ports:
      - "127.0.0.1:5432:5432"
    environment:
      POSTGRES_DB: connected-db
      POSTGRES_USER: connected-admin
      POSTGRES_PASSWORD: Str0ngP@ss_Ul1!Ul1!
